theme = "congo"
baseURL = "https://dmaslov.dev/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Daniil Maslov | Software Engineering Notes"
copyright = "Daniil Maslov :thinking_face:"

enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

[author]
name = "Daniil Maslov"
image = "img/author.jpg"
links = [
  { email = "mailto:i@dmaslovdev" },
  { dev = "https://dev.to/s0xzwasd" },
  { github = "https://github.com/s0xzwasd" },
  { linkedin = "https://www.linkedin.com/in/dsmaslov/" },
  { reddit = "https://reddit.com/user/s0xzwasd" },
  { twitter = "https://twitter.com/s0xzwasd" }
]
